In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import numpy as np

In [3]:
iphone_df = pd.read_csv('iphone.csv')
iphone_df

      Unnamed: 0         출시일  디스플레이  메모리     출시 버전 Face ID
0       iPhone 7  2016-09-16    4.7  2GB  iOS 10.0      No
1  iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
2       iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
3  iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
4       iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
5      iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes
6  iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [5]:
iphone_df = pd.read_csv('iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [7]:
iphone_df['iPhone 8', '메모리']
# unavailable, does not work as a list

KeyError: ('iPhone 8', '메모리')

In [9]:
# "loc" necessary!, when one row line is important, one data-point is important
# df.loc[record/index , feature]
iphone_df.loc['iPhone 8', '메모리']
type(iphone_df.loc['iPhone 8', '메모리'])

'2GB'

str

In [21]:
# one row = 'Series'
iphone_df.loc['iPhone 8', :]
iphone_df.loc['iPhone 8'] # loc : row first, column conditional
type(iphone_df.loc['iPhone 8', :])

# multiple rows = DataFrame
# df.loc[ [rows] ], [rows] ex. ['iPhone 8', 'iPhone X'], ['iPhone 8':'iPhone X']
iphone_df.loc[['iPhone 8', 'iPhone X']]
type(iphone_df.loc[['iPhone 8', 'iPhone X']])

출시일        2017-09-22
디스플레이             4.7
메모리               2GB
출시 버전        iOS 11.0
Face ID            No
Name: iPhone 8, dtype: object

출시일        2017-09-22
디스플레이             4.7
메모리               2GB
출시 버전        iOS 11.0
Face ID            No
Name: iPhone 8, dtype: object

pandas.core.series.Series

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes

pandas.core.frame.DataFrame

In [20]:
# one column = 'Series' : one line = 'Series'
iphone_df['출시일'] # calling one column doesn't need loc
type(iphone_df['출시일'])


# multi columns need list of columns -> df[ [column list] ]
iphone_df[['출시일', '메모리']] # row first, so multiple columns need list of cols
type(iphone_df[['출시일', '메모리']]) # multilines = DataFrame

iphone_df['출시일':'메모리'] # doesn't work absolutely
iphone_df.loc[:, '출시일':'메모리'] # loc necessarily needs row num
type(iphone_df.loc[:, '출시일':'메모리'])


# always remember we need 'row > column'
# one row
# multi row : 1. by list 2. by indexing > they work the same

# one column
# multi column : 1. by list      works same as one column
#                2. by indexing  need "loc"!

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

pandas.core.series.Series

                      출시일  메모리
iPhone 7       2016-09-16  2GB
iPhone 7 Plus  2016-09-16  3GB
iPhone 8       2017-09-22  2GB
iPhone 8 Plus  2017-09-22  3GB
iPhone X       2017-11-03  3GB
iPhone XS      2018-09-21  4GB
iPhone XS Max  2018-09-21  4GB

pandas.core.frame.DataFrame

Empty DataFrame
Columns: [출시일, 디스플레이, 메모리, 출시 버전, Face ID]
Index: []

                      출시일  디스플레이  메모리
iPhone 7       2016-09-16    4.7  2GB
iPhone 7 Plus  2016-09-16    5.5  3GB
iPhone 8       2017-09-22    4.7  2GB
iPhone 8 Plus  2017-09-22    5.5  3GB
iPhone X       2017-11-03    5.8  3GB
iPhone XS      2018-09-21    5.8  4GB
iPhone XS Max  2018-09-21    6.5  4GB

pandas.core.frame.DataFrame

In [24]:
# 13. Conditional Indexing
iphone_df['디스플레이'] > 5
type(iphone_df['디스플레이'] > 5)
# still, series

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

pandas.core.series.Series

In [33]:
# turn lights on : row
iphone_df[[True, False, True, False, True, True, False]] # format used frequently ... alias
iphone_df.loc[[True, False, True, False, True, True, False]]
iphone_df.loc[[True, False, True, False, True, True, False], :] # the above actually means

# if value suffers, rest of them sets to false
#iphone_df[[True, False, True, False, True]] > this doesn't work
iphone_df.loc[[True, False, True, False, True]]

                  출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7   2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8   2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X   2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes

                  출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7   2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8   2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X   2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes

                  출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7   2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8   2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X   2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7  2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes

In [34]:
# turn on lights on columns
iphone_df.loc[:, [True, False, False, True]]

                      출시일     출시 버전
iPhone 7       2016-09-16  iOS 10.0
iPhone 7 Plus  2016-09-16  iOS 10.0
iPhone 8       2017-09-22  iOS 11.0
iPhone 8 Plus  2017-09-22  iOS 11.0
iPhone X       2017-11-03  iOS 11.1
iPhone XS      2018-09-21  iOS 12.0
iPhone XS Max  2018-09-21  iOS 12.0

In [39]:
iphone_df['디스플레이'] > 5 # pd.Series of boolean > we can use this as condition

iphone_df.loc[iphone_df['디스플레이'] > 5]
iphone_df.loc[iphone_df['디스플레이'] > 5, [True, False]]

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

                      출시일
iPhone 7 Plus  2016-09-16
iPhone 8 Plus  2017-09-22
iPhone X       2017-11-03
iPhone XS      2018-09-21
iPhone XS Max  2018-09-21

In [42]:
iphone_df['Face ID'] == "Yes" # condition for each row

iphone_df.loc[iphone_df['Face ID'] == "Yes"]
iphone_df.loc[iphone_df['Face ID'] == "Yes", [True, True, False]]

iPhone 7         False
iPhone 7 Plus    False
iPhone 8         False
iPhone 8 Plus    False
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: Face ID, dtype: bool

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

                      출시일  디스플레이
iPhone X       2017-11-03    5.8
iPhone XS      2018-09-21    5.8
iPhone XS Max  2018-09-21    6.5

In [46]:
# using multiple condition
condition1 = iphone_df['Face ID'] == "No"
condition2 = iphone_df['디스플레이'] > 5

iphone_df.loc[condition1 & condition2]
iphone_df.loc[condition1 | condition2]
iphone_df[condition1]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No